In [ ]:
import numpy as np

Ques1

In [ ]:
arr=np.array([1,2,3,4,5,6])
arr

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr+2

array([3, 4, 5, 6, 7, 8])

In [ ]:
arr*3

array([ 3,  6,  9, 12, 15, 18])

In [ ]:
arr/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. ])

ques2

In [ ]:
arr=np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
rev_arr=arr[::-1]
rev_arr

array([5, 4, 3, 2, 1])

In [ ]:
x=np.array([1,2,3,4,5,1,2,1,1,1])
y=np.array([1,1,1,2,3,4,2,4,3,3])

In [ ]:
values,counts = np.unique(y, return_counts=True)
most_frequent = values[np.argmax(counts)]

indices = np.where(x == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)

Most frequent value: 1
Frequency: 3
Indices: [0 5 7 8 9]


In [ ]:
values,counts = np.unique(y, return_counts=True)

most_frequent = values[np.argmax(counts)]

indices = np.where(y == most_frequent)[0]

print("Most frequent value:", most_frequent)
print("Frequency:", np.max(counts))
print("Indices:", indices)

Most frequent value: 1
Frequency: 3
Indices: [0 1 2]


ques3

In [ ]:
arr=np.array([[10,20,30],[40,50,60],[70,80,90]])
arr

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [ ]:
arr[0,1]

np.int64(20)

In [ ]:
arr[2,0]

np.int64(70)

ques4

In [ ]:
abhinav=np.linspace(10,100,25)
abhinav

array([ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
        40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
        70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
       100.  ])

In [ ]:
abhinav.ndim

1

In [ ]:
abhinav.shape

(25,)

In [ ]:
abhinav.size

25

In [ ]:
abhinav.dtype

dtype('float64')

In [ ]:
abhinav.nbytes

200

In [ ]:
transpose=abhinav.reshape(1,25)
transpose

array([[ 10.  ,  13.75,  17.5 ,  21.25,  25.  ,  28.75,  32.5 ,  36.25,
         40.  ,  43.75,  47.5 ,  51.25,  55.  ,  58.75,  62.5 ,  66.25,
         70.  ,  73.75,  77.5 ,  81.25,  85.  ,  88.75,  92.5 ,  96.25,
        100.  ]])

In [ ]:
transpose.T

array([[ 10.  ],
       [ 13.75],
       [ 17.5 ],
       [ 21.25],
       [ 25.  ],
       [ 28.75],
       [ 32.5 ],
       [ 36.25],
       [ 40.  ],
       [ 43.75],
       [ 47.5 ],
       [ 51.25],
       [ 55.  ],
       [ 58.75],
       [ 62.5 ],
       [ 66.25],
       [ 70.  ],
       [ 73.75],
       [ 77.5 ],
       [ 81.25],
       [ 85.  ],
       [ 88.75],
       [ 92.5 ],
       [ 96.25],
       [100.  ]])

ques5

In [ ]:
ucs420_abhinav=np.array([[10,20,30,40],[50,60,70,80],[90,15,20,35]])
ucs420_abhinav

array([[10, 20, 30, 40],
       [50, 60, 70, 80],
       [90, 15, 20, 35]])

In [ ]:
np.mean(ucs420_abhinav)

np.float64(43.333333333333336)

In [ ]:
np.median(ucs420_abhinav)

np.float64(37.5)

In [ ]:
np.max(ucs420_abhinav)

np.int64(90)

In [ ]:
np.min(ucs420_abhinav)

np.int64(10)

In [ ]:
np.unique(ucs420_abhinav)

array([10, 15, 20, 30, 35, 40, 50, 60, 70, 80, 90])

In [ ]:
reshaped_ucs420_abhinav = ucs420_abhinav.reshape(4, 3)
reshaped_ucs420_abhinav

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90],
       [15, 20, 35]])

In [ ]:
resized_ucs420_abhinav = np.resize(ucs420_abhinav, (2, 3))
resized_ucs420_abhinav

array([[10, 20, 30],
       [40, 50, 60]])