In [ ]:
import numpy as np

ques1

In [ ]:
temperature=np.array([25,28,31,35,38,27,33,40])
temperature

array([25, 28, 31, 35, 38, 27, 33, 40])

In [ ]:
cor_temperature=temperature+2
cor_temperature

array([27, 30, 33, 37, 40, 29, 35, 42])

In [ ]:
fahr=(9/5)*cor_temperature+32
fahr

array([ 80.6,  86. ,  91.4,  98.6, 104. ,  84.2,  95. , 107.6])

In [ ]:
cor_temperature[cor_temperature>32]

array([33, 37, 40, 35, 42])

In [ ]:
count=np.sum(cor_temperature>32)
count

np.int64(5)

ques2

In [ ]:
steps=np.array([[5000,6200,7100],[8000,7500,9000],[4500,5100,4800],[9000,8500,9500]])
steps

array([[5000, 6200, 7100],
       [8000, 7500, 9000],
       [4500, 5100, 4800],
       [9000, 8500, 9500]])

In [ ]:
np.sum(steps)

np.int64(84200)

In [ ]:
np.mean(steps)

np.float64(7016.666666666667)

In [ ]:
np.max(steps)

np.int64(9500)

In [ ]:
np.min(steps)

np.int64(4500)

In [ ]:
np.sum(steps,axis=0)

array([26500, 27300, 30400])

In [ ]:
np.sum(steps,axis=1)

array([18300, 24500, 14400, 27000])

In [ ]:
max_position = np.argmax(steps)
max_position


np.int64(11)

In [ ]:
position = np.unravel_index(max_position, steps.shape)
position

(np.int64(3), np.int64(2))

ques3


In [ ]:
original=np.array([1,2,3,4,5,6])
original

array([1, 2, 3, 4, 5, 6])

In [ ]:
subset=original[0:4]
subset

array([1, 2, 3, 4])

In [ ]:
subset[0]=999
subset

array([999,   2,   3,   4])

In [ ]:
original

array([999,   2,   3,   4,   5,   6])

In [ ]:
copy_array=original.copy()
copy_array

array([999,   2,   3,   4,   5,   6])

In [ ]:
copy_array[0]=500
copy_array

array([500,   2,   3,   4,   5,   6])

In [ ]:
original

array([999,   2,   3,   4,   5,   6])

In [ ]:
arr=np.arange(1,13).reshape(3,4)
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr[0]

array([1, 2, 3, 4])

In [ ]:
arr[-1]

array([ 9, 10, 11, 12])

In [ ]:
arr[:,1:2]

array([[ 2],
       [ 6],
       [10]])

In [ ]:
arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

In [ ]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
ravel_arr=arr.ravel()
ravel_arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [ ]:
ravel_arr[0]=100

In [ ]:
ravel_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [ ]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
flat_arr=arr.flatten()
flat_arr

array([100,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [ ]:
flat_arr[0]=200
flat_arr

array([200,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12])

In [ ]:
arr

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [ ]:
arr.shape

(3, 4)

In [ ]:
arr.ndim

2

In [ ]:
arr.size

12

In [ ]:
arr.dtype

dtype('int64')